# (1) Create "application.yaml" file as below with filled variables ${DATABASE_...}.
spring:
  application:
    name: kensaku-be

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

# (2) In fist run time only, uncomment the following lines for table auto-generation:
#  jpa:
#    hibernate:
#      ddl-auto: update
