# (1) Create "application.yaml" file as below
# (2) Pass your database information here
spring:
  application:
    name: kensaku-be

  datasource:
    url: ${YOUR_DATABASE_URL}                 # <-- Pass here
    username: ${YOUR_DATABASE_USERNAME}       # <-- Pass here
    password: ${YOUR_DATABASE_PASSWORD}       # <-- Pass here
    driverClassName: org.postgresql.Driver

# (3) In fist run time only, uncomment the following lines for table auto-generation:
#  jpa:
#    hibernate:
#      ddl-auto: update

# (4) Pass your security information here
security:
  fe:
    url: "${YOUR_FRONTEND_URL}"               # <-- Pass here
  be:
    public-paths: "/sign-up,/sign-in,/reset-password,/search/**"
  db:
    redis:
      host: ${YOUR_REDIS_HOST}                # <-- Pass here
      port: ${YOUR_REDIS_PORT}                # <-- Pass here
  jwt:
    access-token:
      validity-minutes: 30
    refresh-token:
      validity-days: 30
    encode:
      secret-key: "${YOUR_ENCORE_SECRET_KEY}" # <-- Pass here
    decode:
      secret-key: "${YOUR_ENCORE_SECRET_KEY}" # <-- Pass here
